@base_url=http://localhost:3005
@empresa_url={{base_url}}/empresa
@login_url={{base_url}}/auth/login
@register_url={{base_url}}/auth/register

## CREATE EMPRESA
POST {{empresa_url}}/create
Content-Type: application/json

{
  "nameSponsor": "HELPNEI",
  "descriptionTitle": "TITULO",
  "descriptionSponsor": "Uma descrição detalhada.",
  "exclusiveUrl": "url-exclusiva",
  "sponsorLogo": "https://exemplo.com/logo.png",
  "site_web": "https://exemplo.com",
  "urlSponsor": "https://exemplo.com/sponsor",
  "whatsapp": "https://wa.me/5511999999999",
  "facebook": "https://facebook.com/patrocinador"
}


###

## REMOVE EMPRESA BY ID
DELETE {{empresa_url}}/1

###

## GET ALL EMPRESAS
GET {{empresa_url}}/

###

## GET EMPRESA BY ID
GET {{empresa_url}}/2

### 

## UPDATE EMPRESA BY ID
PATCH {{empresa_url}}/2
Content-Type: application/json

{
  "nameSponsor": "Patrocinador Atualizado",
  "descriptionTitle": "Título Atualizado",
  "descriptionSponsor": "Uma descrição atualizada do patrocinador.",
  "exclusiveUrl": "url-exclusiva-atualizada",
  "sponsorLogo": "https://exemplo.com/logo-atualizada.png",
  "site_web": "https://exemplo.com",
  "urlSponsor": "https://exemplo.com/sponsor/atualizado",
  "whatsapp": "55 11 98888-8888",
  "facebook": "https://facebook.com/patrocinadorAtualizado",
  "instagram": "https://instagram.com/patrocinadorAtualizado",
  "linkedin": "https://linkedin.com/in/patrocinadorAtualizado",
  "tiktok": "https://tiktok.com/@patrocinadorAtualizado",
  "kawai": "https://kawai.com/patrocinadorAtualizado",
  "x": "https://x.com/patrocinadorAtualizado",
  "createdAt": "2024-03-19 00:00:00"
}

### 

## INSERT USUARIO
POST {{register_url}}
Content-Type: application/json

{
  "nomeUsuario": "John Doe",
  "emailUsuario": "johndoe@example.com",
  "senhaUsuario": "senhaSegura123",
  "dataNasc": "1990-05-01",
  "telUsuario": "+55 11 98888-8888",
  "idEmpresaPatrocinio": 58, 
  "idCidade": 24
}

### 

## teste
GET {{base_url}}/auth/test
